### ISSUE TITLE
Uncaught TypeError: NativePromise.resolve is not a function

### ISSUE THREAD

**Issue by pmajhwar** [handsontable/angular-handsontable#34] opened 2017-11-15 07:18 UTC
### Steps to reproduce

1. Bootstrap an angular 4 application
2. follow steps here --> https://handsontable.github.io/angular-handsontable/quick-start
to configure handsontable 
3. After running the application you will see the following error.
zone.js:634 Uncaught TypeError: NativePromise.resolve is not a function
    at Object.setNativePromise (zone.js:634)
    at desc.set (zone.js:1028)
    at module.exports (index.umd.js:23472)
    at $export (index.umd.js:19423)
    at Object.eval (index.umd.js:32227)
    at __webpack_require__ (index.umd.js:17700)
    at Object.eval (index.umd.js:43285)
    at __webpack_require__ (index.umd.js:17700)
    at exports.__esModule (index.umd.js:17743)
    at eval (index.umd.js:17746)

### Your environment
* Wrapper version: 
* Browser Name and version: Chrome : Version 61.0.3163.100 (Official Build) (64-bit)
* Operating System: Windows 10

**Comment by AMBudnik** [comment] 2017-11-15 12:52
You're sure that you took point 3 'Import Handsontable before Zone.js'?
did you try to load handsontable PRO as well?

If you share your app I  will take a look at it.

**Comment by pmajhwar** [comment] 2017-11-16 03:37
Hi Aleksandra,
Thank you so much for helping me out.
Yes I had tried import 'Handsontable'; and import 'handsontable'; in /src/polyfills.ts file.
Please find my app attached.

Kind regards,
Prashant

[app-handsontable.zip](https://github.com/handsontable/angular-handsontable/files/1477236/app-handsontable.zip)

**Comment by AMBudnik** [comment] 2017-11-16 09:28
I am really sorry but I wasn't able to find the cause. Would it help if I send you a copy of my sample app?

**Comment by pmajhwar** [comment] 2017-11-16 12:11
Oh, Sure please send it across, will try it if it works then it would be helpful. If it doesn't then we need to look deeper into the issue. By the way have tried it with latest angular-cli. try running npm update and then I hope you would be able to reproduce it.

Kind regards,
Prashant

**Comment by AMBudnik** [comment] 2017-11-16 12:43
Here you are https://we.tl/mn0o9GmNHD

**Comment by garecinos4** [comment] 2017-11-16 18:23
I have the same error, @pmajhwar Did you find the soluction??

**Comment by davidtaewookim** [comment] 2017-11-16 22:50
I have same error with angular-cli 1.5 (angular 5.0)

Freshly created app with angular-cli 1.5, and setup only handsontable, no other packages or settings added.

**Comment by pmajhwar** [comment] 2017-11-17 02:23
Hi Aleksandra,

Handontable seems to be working with your app, thank you so much.
But after upgrading angular-cli to latest i.e.     "@angular/cli": "^1.5.2", it has started throwing the error mentioned below. Can you please help.
Kind regards 

ng:///AppModule/AppComponent.ngfactory.js:14 ERROR TypeError: handsontable_1.default is not a constructor
    at eval (webpack-internal:///../../../../angular-handsontable/src/hot-table.component.ts:170)
    at ZoneDelegate.invoke (webpack-internal:///../../../../zone.js/dist/zone.js:392)
    at Zone.run (webpack-internal:///../../../../zone.js/dist/zone.js:142)
    at NgZone.runOutsideAngular (webpack-internal:///../../../core/@angular/core.es5.js:4048)
    at HotTableComponent.ngAfterContentInit (webpack-internal:///../../../../angular-handsontable/src/hot-table.component.ts:169)
    at callProviderLifecycles (webpack-internal:///../../../core/@angular/core.es5.js:11400)
    at callElementProvidersLifecycles (webpack-internal:///../../../core/@angular/core.es5.js:11381)
    at callLifecycleHooksChildrenFirst (webpack-internal:///../../../core/@angular/core.es5.js:11365)
    at checkAndUpdateView (webpack-internal:///../../../core/@angular/core.es5.js:12470)
    at callViewAction (webpack-internal:///../../../core/@angular/core.es5.js:12835)
View_AppComponent_0 @ ng:///AppModule/AppComponent.ngfactory.js:14
ng:///AppModule/AppComponent.ngfactory.js:14 ERROR CONTEXT DebugContext_

**Comment by pmajhwar** [comment] 2017-11-17 02:24
Hi @garecinos4 , please try sample app that Aleksandra shared, it's working perfectly.

kind regards

**Comment by pmajhwar** [comment] 2017-11-17 02:26
Hi @davidtaewookim, yes i think angular-cli 1.5 seems to be having issues. I am using 1.4.3 for now.

**Comment by garecinos4** [comment] 2017-11-17 20:40
@pmajhwar @AMBudnik  thanks

But this works for me 

First change 

> import { HotTableModule } from 'angular-handsontable/index';

 in app.module.ts instead 

> import { HotTableModule } from 'angular-handsontable';

in file polyfills.ts I change this 
**import 'handsontable';**  for  **import  'angular-handsontable';**

Then put it in main.ts instead polyfills.ts
>  import 'zone.js/dist/zone';  // Included with Angular CLI.

Finally install the handsontable to recognize the file .css 


Regards

**Comment by avifatal** [comment] 2017-11-18 20:46
is there a solution for that?
this is my sample repo.  https://github.com/avifatal/hottest and its happening there. 
workaround?
thanks

**Comment by pmajhwar** [comment] 2017-11-20 03:21
Hi @avifatal I pulled your repo but getting, can you please check!

ERROR in src/app/app.module.ts(3,32): error TS2307: Cannot find module 'angular-handsontable'.

**Comment by avifatal** [comment] 2017-11-20 05:49
@pmajhwar thank you for trying to help. I just solved it by taking the following rows to main.ts:
```
import 'angular-handsontable';
import 'zone.js/dist/zone';
```
now its working.
Thanks again.

**Comment by pmajhwar** [comment] 2017-11-20 06:07
@avifatal awesome!!

Kind regards

**Comment by linktothapast** [comment] 2017-11-20 19:00
I'm positive this solution **does not work** with `--aot`. There's a separate, related discussion here: https://github.com/handsontable/angular-handsontable/issues/17

**Comment by PaoloneM** [comment] 2017-11-23 14:23
@avifatal solution worked for me but I also had to upgrade node from 6.x.x to 8.6.x or 9.2.x

**Comment by linktothapast** [comment] 2017-11-23 14:34
@PaoloneM Did you compile using `--aot`?

**Comment by PaoloneM** [comment] 2017-11-23 14:47
@linktothapast no, just moved imports from polyfills.ts to main.ts, upgraded ng-cli to 1.5.x, upgraded node, than npm install && ng serve

**Comment by linktothapast** [comment] 2017-11-23 14:48
@PaoloneM I see. Most solutions work during development (`ng serve`), but none with AoT (`ng build --prod --aot`)

**Comment by angexis** [comment] 2017-11-27 21:25
This seems to be due to a packaging issue... not sure why this project should be webpacked since the Angular client code will pack it as well...

I had it working by
1. cloning this repo next to my project
2. adding following package.json into the dist folder
3. changing dependency within my own package.json to point to the source code

Tested with Angular 5.0.3, CLI 1.5.0 and both `ng serve` and `ng build --prod --aot`

My `package.json`
```json
dependencies: {
...
        "angular-handsontable": "link:../angular-handsontable/dist",
...
}
```

The package.json I added to the source repo in `.../angular-handsontable/dist`
```json
{
  "name": "angular-handsontable",
  "version": "1.0.0-beta3",
  "description": "Official Angular 2 directive for Handsontable",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/handsontable/angular-handsontable.git"
  },
  "main": "index.js",
  "typings": "index.d.ts",
  "author": "Handsoncode <hello@handsontable.com>",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/handsontable/angular-handsontable/issues"
  },
  "peerDependencies": {
    "@angular/core": "^2.4.7 || ^5.0.0"
  },
  "dependencies": {
    "handsontable": "0.34.4"
  }
}
```

You have to npm install (or yarn) in your project after linking your dependency to the folder next door.

Hope this workaround helps someone else who was stuck as I was ;)

**Comment by linktothapast** [comment] 2017-11-28 21:38
@angexis Thanks so much for sharing. This did the trick for me, although I still see a few warnings after compilation. But it does work with `--aot` 👍

**Comment by angexis** [comment] 2017-11-28 21:45
@linktothapast you're very welcome!

**Comment by vvaldersteins** [comment] 2017-12-04 09:32
Still did not fix the issue for me after moving the zone and angular-handsontable from polyfills to main.ts

Did not fix the issue after downgrading the angular-cli.

Any other suggestions or fix?

**Comment by AMBudnik** [comment] 2017-12-05 12:56
Hi Guys. I just wanted to share our new findings. 
The new angular-cli does not allow us to use Handsontable PRO. We will update the wrapper at the beginning of 2018.

**Comment by david-j-lee** [comment] 2017-12-06 21:33
Hi @AMBudnik I tried to download your project at the link https://we.tl/mn0o9GmNHD from your prior comment, but the link is dead now. Is it possible to upload it again so I can get my hands on it? Thank you.

**Comment by AMBudnik** [comment] 2017-12-11 08:59
Sure @david-j-lee 
here's the same file https://we.tl/7ohPpcfdev

**Comment by david-j-lee** [comment] 2017-12-12 00:29
@AMBudnik Thank you! After reviewing your project I figured out it was due to me using a later version of Angular and the CLI. This helped me a ton and now my app is finally up and running.

**Comment by AMBudnik** [comment] 2017-12-12 07:07
Great to hear that @david-j-lee 
I keep my fingers crossed for further progress

**Comment by talktokapildev** [comment] 2017-12-18 13:21
Thanks! this worked for me after adding below lines in main.ts

import 'angular-handsontable';
import 'zone.js/dist/zone';

**Comment by mallikcheripally** [comment] 2017-12-20 06:17
This setup worked for me with **Angular 5.1.1**, **Angular CLI 1.6**, **angular-handsontable 1.0.0-beta3**. 

I removed the `zone.js` import in `polyfills.ts` file and imported it into `main.ts` file like this:

`import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import 'zone.js/dist/zone';
import { environment } from './environments/environment';`

In the `polyfills.ts` file, for the **_DEV_** build without AOT, I imported `import 'angular-handsontable';` and for the **_PROD_** build with AOT, I replaced it with `import 'handsontable';`

**Comment by swistach** [comment] 2018-01-11 11:31
Since `zone.js@0.8.19` it's no longer required to modify `polyfills.ts`.
https://stackblitz.com/edit/angular-handsontable-basic-conf
I have checked local angular-cli app, and everything works perfectly with __Angular ^5.0.0__, __Angular CLI 1.6__

**Comment by vvaldersteins** [comment] 2018-01-18 08:34
@swistach Still not working with Angular 4.x . Are there any solutions for it?

**Comment by swistach** [comment] 2018-01-18 10:44
@vvaldersteins, what version of `zone.js` are you using?
Try remove `package-lock.json`, `node_modules, change `zone.js` version to `0.8.19` and then run `npm i`.

This example works: https://stackblitz.com/edit/angular-handsontable-basic-conf-angular4 (also installed on my local machine).

**Comment by swistach** [comment] 2018-02-20 09:29
I suppose that wrapper works with suggested instructions. So, now I close this issue, but you can reopen it if you still have problems related to `zone.js`.

**Closed by swistach** 2018-02-20 09:29 UTC
Labels: Status: Answered
