### ISSUE TITLE
Handsontable instance failed to render view after calling render()

### ISSUE THREAD

**Issue by tanhengyeow** [handsontable/angular-handsontable#140] opened 2019-01-17 05:04 UTC
### Description
I was working on some logic that hides the spreadsheet interface upon a boolean condition using `div [hidden]="condition"`>. A HOT instance is placed inside this `div` element. Upon toggling between the views of the spreadsheet (hidden/visible), calling the `render()` function did not render the spreadsheet interface as expected.

### Steps to reproduce

1. Place a HOT instance inside a `div` element e.g. `div [hidden]="condition"`
2. Write some JS logic to toggle the condition (bool)
3. Call `.render()` on the spreadsheet instance
4. View of the spreadsheet interface remains buggy

### Your environment
* Angular version: 7
* Handsontable version: 6.2.2
* Wrapper version: 3.0.0
* Browser Name and version: Chrome [Version 71.0.3578.98 (Official Build) (64-bit)]
* Operating System: macOS Mojave Version 10.14.2

**Comment by tanhengyeow** [comment] 2019-01-19 10:12
Hi @AMBudnik 

Apparently if I apply the `[hidden]` property e.g. `<hot-table [hidden]="condition"></hot-table>` and toggle the value, the spreadsheet doesn't get rendered nicely.

Calling `.render()` doesn't help too.

**Comment by wojciechczerniak** [comment] 2019-03-07 14:25
Duplicate of https://github.com/handsontable/handsontable/issues/5322. We can track the issue there.

For `render()` or `refreshDimensions()` to work we have to call it when the div is actually visible. `setTimeout` or `mutationObserver` (better) should us help here: https://jsfiddle.net/xfzqtw3p/1/.

**Closed by wojciechczerniak** 2019-03-07 14:25 UTC
Labels: Status: Answered
